---
http_interactions:
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/<%= feed_uuid %>/metricTypes/Total%20Space
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Thu, 05 May 2016 11:18:44 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '232'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/mt;Total%20Space",
          "name" : "Total Space",
          "unit" : "BYTES",
          "type" : "GAUGE",
          "collectionInterval" : 300,
          "id" : "Total Space"
        }
    http_version: 
  recorded_at: Thu, 05 May 2016 11:18:44 GMT
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/path/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/mt;Total%20Space/relationships?named=defines&sort=__targetCp
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Thu, 05 May 2016 11:18:44 GMT
      X-Total-Count:
      - '7'
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '3102'
      Link:
      - <http://localhost:8080/hawkular/inventory/path/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/mt;Total%20Space/relationships?sort=__targetCp&named=defines>;
        rel="current"
    body:
      encoding: ASCII-8BIT
      string: |-
        [ {
          "id" : "1jwg-9hc-1g5x-1erk",
          "name" : "defines",
          "source" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/mt;Total%20Space",
          "target" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/m;MI~R~%5B<%= feed_uuid %>%2Fplatform~%2FOPERATING_SYSTEM%3D<%= feed_uuid %>_OperatingSystem%2FFILE_STORE%3D%2Fdev%2Fmapper%2Ffedora-home%5D~MT~Total%20Space"
        }, {
          "id" : "1iow-9hc-1g5x-1dds",
          "name" : "defines",
          "source" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/mt;Total%20Space",
          "target" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/m;MI~R~%5B<%= feed_uuid %>%2Fplatform~%2FOPERATING_SYSTEM%3D<%= feed_uuid %>_OperatingSystem%2FFILE_STORE%3D%2Fdev%2Fsda3%5D~MT~Total%20Space"
        }, {
          "id" : "1iio-9hc-1g5x-1d6o",
          "name" : "defines",
          "source" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/mt;Total%20Space",
          "target" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/m;MI~R~%5B<%= feed_uuid %>%2Fplatform~%2FOPERATING_SYSTEM%3D<%= feed_uuid %>_OperatingSystem%2FFILE_STORE%3Dhugetlbfs%5D~MT~Total%20Space"
        }, {
          "id" : "1k8w-9hc-1g5x-1f5s",
          "name" : "defines",
          "source" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/mt;Total%20Space",
          "target" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/m;MI~R~%5B<%= feed_uuid %>%2Fplatform~%2FOPERATING_SYSTEM%3D<%= feed_uuid %>_OperatingSystem%2FFILE_STORE%3Dmqueue%5D~MT~Total%20Space"
        }, {
          "id" : "1jk0-9hc-1g5x-1edc",
          "name" : "defines",
          "source" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/mt;Total%20Space",
          "target" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/m;MI~R~%5B<%= feed_uuid %>%2Fplatform~%2FOPERATING_SYSTEM%3D<%= feed_uuid %>_OperatingSystem%2FFILE_STORE%3Dsunrpc%5D~MT~Total%20Space"
        }, {
          "id" : "1i68-9hc-1g5x-1csg",
          "name" : "defines",
          "source" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/mt;Total%20Space",
          "target" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/m;MI~R~%5B<%= feed_uuid %>%2Fplatform~%2FOPERATING_SYSTEM%3D<%= feed_uuid %>_OperatingSystem%2FFILE_STORE%3Dtmpfs%5D~MT~Total%20Space"
        }, {
          "id" : "1j1c-9hc-1g5x-1ds0",
          "name" : "defines",
          "source" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/mt;Total%20Space",
          "target" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/m;MI~R~%5B<%= feed_uuid %>%2Fplatform~%2FOPERATING_SYSTEM%3D<%= feed_uuid %>_OperatingSystem%2FFILE_STORE%3D~%5D~MT~Total%20Space"
        } ]
    http_version: 
  recorded_at: Thu, 05 May 2016 11:18:44 GMT
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/path/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/m;MI~R~%5B<%= feed_uuid %>%2Fplatform~%2FOPERATING_SYSTEM=<%= feed_uuid %>_OperatingSystem%2FFILE_STORE=%2Fdev%2Fmapper%2Ffedora-home%5D~MT~Total%20Space
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Thu, 05 May 2016 11:18:44 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '764'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/m;MI~R~%5B<%= feed_uuid %>%2Fplatform~%2FOPERATING_SYSTEM%3D<%= feed_uuid %>_OperatingSystem%2FFILE_STORE%3D%2Fdev%2Fmapper%2Ffedora-home%5D~MT~Total%20Space",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/mt;Total%20Space",
            "name" : "Total Space",
            "unit" : "BYTES",
            "type" : "GAUGE",
            "collectionInterval" : 300,
            "id" : "Total Space"
          },
          "name" : "Total Space",
          "id" : "MI~R~[<%= feed_uuid %>/platform~/OPERATING_SYSTEM=<%= feed_uuid %>_OperatingSystem/FILE_STORE=/dev/mapper/fedora-home]~MT~Total Space"
        }
    http_version: 
  recorded_at: Thu, 05 May 2016 11:18:44 GMT
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/path/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/m;MI~R~%5B<%= feed_uuid %>%2Fplatform~%2FOPERATING_SYSTEM=<%= feed_uuid %>_OperatingSystem%2FFILE_STORE=%2Fdev%2Fsda3%5D~MT~Total%20Space
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Thu, 05 May 2016 11:18:44 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '734'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/m;MI~R~%5B<%= feed_uuid %>%2Fplatform~%2FOPERATING_SYSTEM%3D<%= feed_uuid %>_OperatingSystem%2FFILE_STORE%3D%2Fdev%2Fsda3%5D~MT~Total%20Space",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/mt;Total%20Space",
            "name" : "Total Space",
            "unit" : "BYTES",
            "type" : "GAUGE",
            "collectionInterval" : 300,
            "id" : "Total Space"
          },
          "name" : "Total Space",
          "id" : "MI~R~[<%= feed_uuid %>/platform~/OPERATING_SYSTEM=<%= feed_uuid %>_OperatingSystem/FILE_STORE=/dev/sda3]~MT~Total Space"
        }
    http_version: 
  recorded_at: Thu, 05 May 2016 11:18:44 GMT
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/path/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/m;MI~R~%5B<%= feed_uuid %>%2Fplatform~%2FOPERATING_SYSTEM=<%= feed_uuid %>_OperatingSystem%2FFILE_STORE=hugetlbfs%5D~MT~Total%20Space
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Thu, 05 May 2016 11:18:44 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '730'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/m;MI~R~%5B<%= feed_uuid %>%2Fplatform~%2FOPERATING_SYSTEM%3D<%= feed_uuid %>_OperatingSystem%2FFILE_STORE%3Dhugetlbfs%5D~MT~Total%20Space",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/mt;Total%20Space",
            "name" : "Total Space",
            "unit" : "BYTES",
            "type" : "GAUGE",
            "collectionInterval" : 300,
            "id" : "Total Space"
          },
          "name" : "Total Space",
          "id" : "MI~R~[<%= feed_uuid %>/platform~/OPERATING_SYSTEM=<%= feed_uuid %>_OperatingSystem/FILE_STORE=hugetlbfs]~MT~Total Space"
        }
    http_version: 
  recorded_at: Thu, 05 May 2016 11:18:44 GMT
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/path/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/m;MI~R~%5B<%= feed_uuid %>%2Fplatform~%2FOPERATING_SYSTEM=<%= feed_uuid %>_OperatingSystem%2FFILE_STORE=mqueue%5D~MT~Total%20Space
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Thu, 05 May 2016 11:18:44 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '724'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/m;MI~R~%5B<%= feed_uuid %>%2Fplatform~%2FOPERATING_SYSTEM%3D<%= feed_uuid %>_OperatingSystem%2FFILE_STORE%3Dmqueue%5D~MT~Total%20Space",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/mt;Total%20Space",
            "name" : "Total Space",
            "unit" : "BYTES",
            "type" : "GAUGE",
            "collectionInterval" : 300,
            "id" : "Total Space"
          },
          "name" : "Total Space",
          "id" : "MI~R~[<%= feed_uuid %>/platform~/OPERATING_SYSTEM=<%= feed_uuid %>_OperatingSystem/FILE_STORE=mqueue]~MT~Total Space"
        }
    http_version: 
  recorded_at: Thu, 05 May 2016 11:18:44 GMT
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/path/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/m;MI~R~%5B<%= feed_uuid %>%2Fplatform~%2FOPERATING_SYSTEM=<%= feed_uuid %>_OperatingSystem%2FFILE_STORE=sunrpc%5D~MT~Total%20Space
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Thu, 05 May 2016 11:18:44 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '724'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/m;MI~R~%5B<%= feed_uuid %>%2Fplatform~%2FOPERATING_SYSTEM%3D<%= feed_uuid %>_OperatingSystem%2FFILE_STORE%3Dsunrpc%5D~MT~Total%20Space",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/mt;Total%20Space",
            "name" : "Total Space",
            "unit" : "BYTES",
            "type" : "GAUGE",
            "collectionInterval" : 300,
            "id" : "Total Space"
          },
          "name" : "Total Space",
          "id" : "MI~R~[<%= feed_uuid %>/platform~/OPERATING_SYSTEM=<%= feed_uuid %>_OperatingSystem/FILE_STORE=sunrpc]~MT~Total Space"
        }
    http_version: 
  recorded_at: Thu, 05 May 2016 11:18:44 GMT
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/path/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/m;MI~R~%5B<%= feed_uuid %>%2Fplatform~%2FOPERATING_SYSTEM=<%= feed_uuid %>_OperatingSystem%2FFILE_STORE=tmpfs%5D~MT~Total%20Space
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Thu, 05 May 2016 11:18:44 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '722'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/m;MI~R~%5B<%= feed_uuid %>%2Fplatform~%2FOPERATING_SYSTEM%3D<%= feed_uuid %>_OperatingSystem%2FFILE_STORE%3Dtmpfs%5D~MT~Total%20Space",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/mt;Total%20Space",
            "name" : "Total Space",
            "unit" : "BYTES",
            "type" : "GAUGE",
            "collectionInterval" : 300,
            "id" : "Total Space"
          },
          "name" : "Total Space",
          "id" : "MI~R~[<%= feed_uuid %>/platform~/OPERATING_SYSTEM=<%= feed_uuid %>_OperatingSystem/FILE_STORE=tmpfs]~MT~Total Space"
        }
    http_version: 
  recorded_at: Thu, 05 May 2016 11:18:44 GMT
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/path/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/m;MI~R~%5B<%= feed_uuid %>%2Fplatform~%2FOPERATING_SYSTEM=<%= feed_uuid %>_OperatingSystem%2FFILE_STORE=~%5D~MT~Total%20Space
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Thu, 05 May 2016 11:18:44 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '714'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/m;MI~R~%5B<%= feed_uuid %>%2Fplatform~%2FOPERATING_SYSTEM%3D<%= feed_uuid %>_OperatingSystem%2FFILE_STORE%3D~%5D~MT~Total%20Space",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/mt;Total%20Space",
            "name" : "Total Space",
            "unit" : "BYTES",
            "type" : "GAUGE",
            "collectionInterval" : 300,
            "id" : "Total Space"
          },
          "name" : "Total Space",
          "id" : "MI~R~[<%= feed_uuid %>/platform~/OPERATING_SYSTEM=<%= feed_uuid %>_OperatingSystem/FILE_STORE=~]~MT~Total Space"
        }
    http_version: 
  recorded_at: Thu, 05 May 2016 11:18:44 GMT
recorded_with: VCR 3.0.1
