---
http_interactions:
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/<%= feed_uuid %>/resourceTypes/WildFly%20Server/resources
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Thu, 21 Apr 2016 00:54:35 GMT
      X-Total-Count:
      - '1'
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '351'
      Link:
      - <http://localhost:8080/hawkular/inventory/feeds/<%= feed_uuid %>/resourceTypes/WildFly%20Server/resources>;
        rel="current"
    body:
      encoding: ASCII-8BIT
      string: |-
        [ {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/r;Local~~",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/rt;WildFly%20Server",
            "name" : "WildFly Server",
            "id" : "WildFly Server"
          },
          "name" : "localhost/Local",
          "id" : "Local~~"
        } ]
    http_version: 
  recorded_at: Thu, 21 Apr 2016 00:54:35 GMT
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/<%= feed_uuid %>/resources/Local~~/data?dataType=configuration
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Thu, 21 Apr 2016 00:54:35 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '351'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/r;Local~~/d;configuration",
          "value" : {
            "Bound Address" : "127.0.0.1",
            "Version" : "1.0.0.Alpha13-SNAPSHOT",
            "Server State" : "running",
            "Product Name" : "Hawkular",
            "Hostname" : "localhost.localdomain"
          },
          "name" : "configuration"
        }
    http_version: 
  recorded_at: Thu, 21 Apr 2016 00:54:35 GMT
recorded_with: VCR 3.0.1
