---
http_interactions:
- request:
    method: post
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/
    body:
      encoding: UTF-8
      string: '{"properties":{},"id":"feed_may_exist","name":null,"outgoing":{},"incoming":{}}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      Content-Length:
      - '79'
      User-Agent:
      - Ruby
  response:
    status:
      code: 201
      message: Created
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Location:
      - http://localhost:8080/hawkular/inventory/feeds/feed_may_exist
      Date:
      - Tue, 10 May 2016 14:55:04 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '100'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist",
          "id" : "feed_may_exist"
        }
    http_version: 
  recorded_at: Tue, 10 May 2016 14:55:04 GMT
- request:
    method: post
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/feed_may_exist/resourceTypes
    body:
      encoding: UTF-8
      string: '{"properties":{},"id":"rt-123","name":"ResourceType","outgoing":{},"incoming":{}}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      Content-Length:
      - '81'
      User-Agent:
      - Ruby
  response:
    status:
      code: 201
      message: Created
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Location:
      - http://localhost:8080/hawkular/inventory/feeds/feed_may_exist/resourceTypes/rt-123
      Date:
      - Tue, 10 May 2016 14:55:04 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '129'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist/rt;rt-123",
          "name" : "ResourceType",
          "id" : "rt-123"
        }
    http_version: 
  recorded_at: Tue, 10 May 2016 14:55:04 GMT
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/feed_may_exist/resourceTypes/rt-123
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Tue, 10 May 2016 14:55:04 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '129'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist/rt;rt-123",
          "name" : "ResourceType",
          "id" : "rt-123"
        }
    http_version: 
  recorded_at: Tue, 10 May 2016 14:55:04 GMT
- request:
    method: post
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/feed_may_exist/resources
    body:
      encoding: UTF-8
      string: '{"properties":{"version":1.0},"id":"r124","name":"My Resource","outgoing":{},"incoming":{},"resourceTypePath":"/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist/rt;rt-123"}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      Content-Length:
      - '179'
      User-Agent:
      - Ruby
  response:
    status:
      code: 201
      message: Created
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Location:
      - http://localhost:8080/hawkular/inventory/feeds/feed_may_exist/resources/r124
      Date:
      - Tue, 10 May 2016 14:55:04 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '317'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist/r;r124",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist/rt;rt-123",
            "name" : "ResourceType",
            "id" : "rt-123"
          },
          "properties" : {
            "version" : 1.0
          },
          "name" : "My Resource",
          "id" : "r124"
        }
    http_version: 
  recorded_at: Tue, 10 May 2016 14:55:04 GMT
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/feed_may_exist/resources/r124
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Tue, 10 May 2016 14:55:04 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '317'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist/r;r124",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist/rt;rt-123",
            "name" : "ResourceType",
            "id" : "rt-123"
          },
          "properties" : {
            "version" : 1.0
          },
          "name" : "My Resource",
          "id" : "r124"
        }
    http_version: 
  recorded_at: Tue, 10 May 2016 14:55:04 GMT
- request:
    method: post
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/feed_may_exist/metricTypes
    body:
      encoding: UTF-8
      string: '{"id":"mt-124","type":"GAUGE","unit":"NONE","collectionInterval":60}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      Content-Length:
      - '68'
      User-Agent:
      - Ruby
  response:
    status:
      code: 201
      message: Created
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Location:
      - http://localhost:8080/hawkular/inventory/feeds/feed_may_exist/metricTypes/mt-124
      Date:
      - Tue, 10 May 2016 14:55:04 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '170'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist/mt;mt-124",
          "unit" : "NONE",
          "type" : "GAUGE",
          "collectionInterval" : 60,
          "id" : "mt-124"
        }
    http_version: 
  recorded_at: Tue, 10 May 2016 14:55:04 GMT
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/feed_may_exist/metricTypes/mt-124
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Tue, 10 May 2016 14:55:05 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '170'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist/mt;mt-124",
          "unit" : "NONE",
          "type" : "GAUGE",
          "collectionInterval" : 60,
          "id" : "mt-124"
        }
    http_version: 
  recorded_at: Tue, 10 May 2016 14:55:05 GMT
- request:
    method: post
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/feed_may_exist/metrics
    body:
      encoding: UTF-8
      string: '{"id":"m-124","name":"m-124","metricTypePath":"/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist/mt;mt-124"}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      Content-Length:
      - '115'
      User-Agent:
      - Ruby
  response:
    status:
      code: 201
      message: Created
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Location:
      - http://localhost:8080/hawkular/inventory/feeds/feed_may_exist/metrics/m-124
      Date:
      - Tue, 10 May 2016 14:55:05 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '314'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist/m;m-124",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist/mt;mt-124",
            "unit" : "NONE",
            "type" : "GAUGE",
            "collectionInterval" : 60,
            "id" : "mt-124"
          },
          "name" : "m-124",
          "id" : "m-124"
        }
    http_version: 
  recorded_at: Tue, 10 May 2016 14:55:05 GMT
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/feed_may_exist/metrics/m-124
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Tue, 10 May 2016 14:55:05 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '314'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist/m;m-124",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist/mt;mt-124",
            "unit" : "NONE",
            "type" : "GAUGE",
            "collectionInterval" : 60,
            "id" : "mt-124"
          },
          "name" : "m-124",
          "id" : "m-124"
        }
    http_version: 
  recorded_at: Tue, 10 May 2016 14:55:05 GMT
- request:
    method: post
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/feed_may_exist/resources/r124/metrics
    body:
      encoding: UTF-8
      string: '["/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist/m;m-124"]'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      Content-Length:
      - '68'
      User-Agent:
      - Ruby
  response:
    status:
      code: 204
      message: No Content
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Tue, 10 May 2016 14:55:05 GMT
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Tue, 10 May 2016 14:55:05 GMT
- request:
    method: post
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/feed_may_exist/metrics
    body:
      encoding: UTF-8
      string: '{"id":"m-124-1","name":"Metric1","metricTypePath":"/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist/mt;mt-124"}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      Content-Length:
      - '119'
      User-Agent:
      - Ruby
  response:
    status:
      code: 201
      message: Created
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Location:
      - http://localhost:8080/hawkular/inventory/feeds/feed_may_exist/metrics/m-124-1
      Date:
      - Tue, 10 May 2016 14:55:05 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '320'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist/m;m-124-1",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist/mt;mt-124",
            "unit" : "NONE",
            "type" : "GAUGE",
            "collectionInterval" : 60,
            "id" : "mt-124"
          },
          "name" : "Metric1",
          "id" : "m-124-1"
        }
    http_version: 
  recorded_at: Tue, 10 May 2016 14:55:05 GMT
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/feed_may_exist/metrics/m-124-1
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Tue, 10 May 2016 14:55:05 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '320'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist/m;m-124-1",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist/mt;mt-124",
            "unit" : "NONE",
            "type" : "GAUGE",
            "collectionInterval" : 60,
            "id" : "mt-124"
          },
          "name" : "Metric1",
          "id" : "m-124-1"
        }
    http_version: 
  recorded_at: Tue, 10 May 2016 14:55:05 GMT
- request:
    method: post
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/feed_may_exist/resources/r124/metrics
    body:
      encoding: UTF-8
      string: '["/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist/m;m-124-1"]'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      Content-Length:
      - '70'
      User-Agent:
      - Ruby
  response:
    status:
      code: 204
      message: No Content
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Tue, 10 May 2016 14:55:05 GMT
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Tue, 10 May 2016 14:55:05 GMT
recorded_with: VCR 3.0.1
