---
http_interactions:
- request:
    method: post
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/
    body:
      encoding: UTF-8
      string: '{"properties":{},"id":"feed_may_exist","name":null,"outgoing":{},"incoming":{}}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      Content-Length:
      - '79'
      User-Agent:
      - Ruby
  response:
    status:
      code: 201
      message: Created
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Location:
      - http://localhost:8080/hawkular/inventory/feeds/feed_may_exist
      Date:
      - Thu, 21 Apr 2016 00:54:40 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '100'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist",
          "id" : "feed_may_exist"
        }
    http_version: 
  recorded_at: Thu, 21 Apr 2016 00:54:40 GMT
- request:
    method: post
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/feed_may_exist/resourceTypes
    body:
      encoding: UTF-8
      string: '{"properties":{},"id":"rt-123","name":"ResourceType","outgoing":{},"incoming":{}}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      Content-Length:
      - '81'
      User-Agent:
      - Ruby
  response:
    status:
      code: 201
      message: Created
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Location:
      - http://localhost:8080/hawkular/inventory/feeds/feed_may_exist/resourceTypes/rt-123
      Date:
      - Thu, 21 Apr 2016 00:54:40 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '129'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist/rt;rt-123",
          "name" : "ResourceType",
          "id" : "rt-123"
        }
    http_version: 
  recorded_at: Thu, 21 Apr 2016 00:54:40 GMT
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/feed_may_exist/resourceTypes/rt-123
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Thu, 21 Apr 2016 00:54:40 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '129'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist/rt;rt-123",
          "name" : "ResourceType",
          "id" : "rt-123"
        }
    http_version: 
  recorded_at: Thu, 21 Apr 2016 00:54:40 GMT
recorded_with: VCR 3.0.1
