---
http_interactions:
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/feed_may_exist/resources/*bla%20does%20not%20exist*
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 404
      message: Not Found
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Mon, 11 Apr 2016 16:51:45 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '372'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "errorMsg" : "No Resource found on any of the following paths: [[CanonicalPaths[/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist/r;%2Abla%20does%20not%20exist%2A]]]",
          "details" : {
            "entityType" : "Resource",
            "path" : [ [ {
              "paths" : [ "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist/r;%2Abla%20does%20not%20exist%2A" ]
            } ] ]
          }
        }
    http_version: 
  recorded_at: Mon, 11 Apr 2016 16:51:45 GMT
recorded_with: VCR 3.0.1
