---
http_interactions:
- request:
    method: post
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/
    body:
      encoding: UTF-8
      string: '{"properties":{},"id":"feed_1123sdn","name":null,"outgoing":{},"incoming":{}}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      Content-Length:
      - '77'
      User-Agent:
      - Ruby
  response:
    status:
      code: 201
      message: Created
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Location:
      - http://localhost:8080/hawkular/inventory/feeds/feed_1123sdn
      Date:
      - Thu, 21 Apr 2016 00:54:39 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '96'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_1123sdn",
          "id" : "feed_1123sdn"
        }
    http_version: 
  recorded_at: Thu, 21 Apr 2016 00:54:39 GMT
- request:
    method: delete
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/feed_1123sdn
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 204
      message: No Content
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Thu, 21 Apr 2016 00:54:39 GMT
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Thu, 21 Apr 2016 00:54:39 GMT
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Thu, 21 Apr 2016 00:54:39 GMT
      X-Total-Count:
      - '2'
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '294'
      Link:
      - <http://localhost:8080/hawkular/inventory/feeds>; rel="current"
    body:
      encoding: ASCII-8BIT
      string: |-
        [ {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>",
          "id" : "<%= feed_uuid %>"
        }, {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_1123sdncisud6237ui23hjbdscuzsad",
          "id" : "feed_1123sdncisud6237ui23hjbdscuzsad"
        } ]
    http_version: 
  recorded_at: Thu, 21 Apr 2016 00:54:39 GMT
recorded_with: VCR 3.0.1
