---
http_interactions:
- request:
    method: post
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/
    body:
      encoding: UTF-8
      string: '{"properties":{},"id":"feed_may_exist","name":null,"outgoing":{},"incoming":{}}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      Content-Length:
      - '79'
      User-Agent:
      - Ruby
  response:
    status:
      code: 409
      message: Conflict
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Thu, 05 May 2016 11:18:45 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '747'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "errorMsg" : "Feed with id 'Feed[path='/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist']' has been already registered. Entity with id 'feed_may_exist' already exists at some of the positions: [[Types[Tenant], Ids[28026b36-8fe4-4332-84c8-524e173a68bf], Related[, rel='contains', role=SOURCE], Types[Feed], Ids[feed_may_exist]]]",
          "details" : {
            "entityId" : "feed_may_exist",
            "paths" : [ [ {
              "types" : [ "org.hawkular.inventory.api.model.Tenant" ]
            }, {
              "ids" : [ "28026b36-8fe4-4332-84c8-524e173a68bf" ]
            }, {
              "relationshipName" : "contains",
              "entityRole" : "SOURCE"
            }, {
              "types" : [ "org.hawkular.inventory.api.model.Feed" ]
            }, {
              "ids" : [ "feed_may_exist" ]
            } ] ]
          }
        }
    http_version: 
  recorded_at: Thu, 05 May 2016 11:18:45 GMT
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/feed_may_exist
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Thu, 05 May 2016 11:18:45 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '100'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist",
          "id" : "feed_may_exist"
        }
    http_version: 
  recorded_at: Thu, 05 May 2016 11:18:45 GMT
- request:
    method: post
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/feed_may_exist/resourceTypes
    body:
      encoding: UTF-8
      string: '{"properties":{},"id":"rt-123","name":"ResourceType","outgoing":{},"incoming":{}}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      Content-Length:
      - '81'
      User-Agent:
      - Ruby
  response:
    status:
      code: 409
      message: Conflict
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Thu, 05 May 2016 11:18:45 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '107'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "errorMsg" : "Entity with id 'null' already exists at some of the positions: null",
          "details" : { }
        }
    http_version: 
  recorded_at: Thu, 05 May 2016 11:18:45 GMT
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/feed_may_exist/resourceTypes/rt-123
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Thu, 05 May 2016 11:18:45 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '129'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist/rt;rt-123",
          "name" : "ResourceType",
          "id" : "rt-123"
        }
    http_version: 
  recorded_at: Thu, 05 May 2016 11:18:45 GMT
- request:
    method: post
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/feed_may_exist/resources
    body:
      encoding: UTF-8
      string: '{"properties":{"version":1.0},"id":"r123","name":"My Resource","outgoing":{},"incoming":{},"resourceTypePath":"/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist/rt;rt-123"}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      Content-Length:
      - '179'
      User-Agent:
      - Ruby
  response:
    status:
      code: 201
      message: Created
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Location:
      - http://localhost:8080/hawkular/inventory/feeds/feed_may_exist/resources/r123
      Date:
      - Thu, 05 May 2016 11:18:46 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '317'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist/r;r123",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist/rt;rt-123",
            "name" : "ResourceType",
            "id" : "rt-123"
          },
          "properties" : {
            "version" : 1.0
          },
          "name" : "My Resource",
          "id" : "r123"
        }
    http_version: 
  recorded_at: Thu, 05 May 2016 11:18:46 GMT
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/feed_may_exist/resources/r123
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Thu, 05 May 2016 11:18:46 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '317'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist/r;r123",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist/rt;rt-123",
            "name" : "ResourceType",
            "id" : "rt-123"
          },
          "properties" : {
            "version" : 1.0
          },
          "name" : "My Resource",
          "id" : "r123"
        }
    http_version: 
  recorded_at: Thu, 05 May 2016 11:18:46 GMT
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/feed_may_exist/resources/r123
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Thu, 05 May 2016 11:18:46 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '317'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist/r;r123",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist/rt;rt-123",
            "name" : "ResourceType",
            "id" : "rt-123"
          },
          "properties" : {
            "version" : 1.0
          },
          "name" : "My Resource",
          "id" : "r123"
        }
    http_version: 
  recorded_at: Thu, 05 May 2016 11:18:46 GMT
recorded_with: VCR 3.0.1
