---
http_interactions:
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/<%= feed_uuid %>/resourceTypes/WildFly%20Server/resources
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Mon, 11 Apr 2016 16:51:39 GMT
      X-Total-Count:
      - '1'
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '357'
      Link:
      - <http://localhost:8080/hawkular/inventory/feeds/<%= feed_uuid %>/resourceTypes/WildFly%20Server/resources>;
        rel="current"
    body:
      encoding: ASCII-8BIT
      string: |-
        [ {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/r;Local~~",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/rt;WildFly%20Server",
            "name" : "WildFly Server",
            "id" : "WildFly Server"
          },
          "name" : "dhcp-10-40-1-43/Local",
          "id" : "Local~~"
        } ]
    http_version: 
  recorded_at: Mon, 11 Apr 2016 16:51:39 GMT
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/<%= feed_uuid %>/resources/Local~~/children
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Mon, 11 Apr 2016 16:51:39 GMT
      X-Total-Count:
      - '22'
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '9615'
      Link:
      - <http://localhost:8080/hawkular/inventory/feeds/<%= feed_uuid %>/resources/Local~~/children>;
        rel="current"
    body:
      encoding: ASCII-8BIT
      string: |-
        [ {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/r;Local~~/r;Local~%2Fsubsystem%3Ddatasources%2Fdata-source%3DExampleDS",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/rt;Datasource",
            "name" : "Datasource",
            "id" : "Datasource"
          },
          "name" : "ExampleDS",
          "id" : "Local~/subsystem=datasources/data-source=ExampleDS"
        }, {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/r;Local~~/r;Local~%2Fsubsystem%3Ddatasources%2Fdata-source%3DKeycloakDS",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/rt;Datasource",
            "name" : "Datasource",
            "id" : "Datasource"
          },
          "name" : "KeycloakDS",
          "id" : "Local~/subsystem=datasources/data-source=KeycloakDS"
        }, {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/r;Local~~/r;Local~%2Fsubsystem%3Ddatasources%2Fjdbc-driver%3Dh2",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/rt;JDBC%20Driver",
            "name" : "JDBC Driver",
            "id" : "JDBC Driver"
          },
          "name" : "h2",
          "id" : "Local~/subsystem=datasources/jdbc-driver=h2"
        }, {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/r;Local~~/r;Local~%2Fdeployment%3Dhawkular-command-gateway-war.war",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/rt;Deployment",
            "name" : "Deployment",
            "id" : "Deployment"
          },
          "name" : "hawkular-command-gateway-war.war",
          "id" : "Local~/deployment=hawkular-command-gateway-war.war"
        }, {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/r;Local~~/r;Local~%2Fdeployment%3Dhawkular-alerts-actions-email.war",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/rt;Deployment",
            "name" : "Deployment",
            "id" : "Deployment"
          },
          "name" : "hawkular-alerts-actions-email.war",
          "id" : "Local~/deployment=hawkular-alerts-actions-email.war"
        }, {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/r;Local~~/r;Local~%2Fdeployment%3Dhawkular-wildfly-agent-download.war",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/rt;Deployment",
            "name" : "Deployment",
            "id" : "Deployment"
          },
          "name" : "hawkular-wildfly-agent-download.war",
          "id" : "Local~/deployment=hawkular-wildfly-agent-download.war"
        }, {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/r;Local~~/r;Local~%2Fdeployment%3Dhawkular-avail-creator.war",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/rt;Deployment",
            "name" : "Deployment",
            "id" : "Deployment"
          },
          "name" : "hawkular-avail-creator.war",
          "id" : "Local~/deployment=hawkular-avail-creator.war"
        }, {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/r;Local~~/r;Local~%2Fdeployment%3Dsecret-store.war",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/rt;Deployment",
            "name" : "Deployment",
            "id" : "Deployment"
          },
          "name" : "secret-store.war",
          "id" : "Local~/deployment=secret-store.war"
        }, {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/r;Local~~/r;Local~%2Fdeployment%3Dhawkular-inventory-dist.war",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/rt;Deployment",
            "name" : "Deployment",
            "id" : "Deployment"
          },
          "name" : "hawkular-inventory-dist.war",
          "id" : "Local~/deployment=hawkular-inventory-dist.war"
        }, {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/r;Local~~/r;Local~%2Fdeployment%3Dhawkular-alerts-rest.war",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/rt;Deployment",
            "name" : "Deployment",
            "id" : "Deployment"
          },
          "name" : "hawkular-alerts-rest.war",
          "id" : "Local~/deployment=hawkular-alerts-rest.war"
        }, {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/r;Local~~/r;Local~%2Fdeployment%3Dhawkular-accounts-events-backend.war",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/rt;Deployment",
            "name" : "Deployment",
            "id" : "Deployment"
          },
          "name" : "hawkular-accounts-events-backend.war",
          "id" : "Local~/deployment=hawkular-accounts-events-backend.war"
        }, {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/r;Local~~/r;Local~%2Fdeployment%3Dhawkular-pinger.war",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/rt;Deployment",
            "name" : "Deployment",
            "id" : "Deployment"
          },
          "name" : "hawkular-pinger.war",
          "id" : "Local~/deployment=hawkular-pinger.war"
        }, {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/r;Local~~/r;Local~%2Fdeployment%3Dhawkular-rest-api.war",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/rt;Deployment",
            "name" : "Deployment",
            "id" : "Deployment"
          },
          "name" : "hawkular-rest-api.war",
          "id" : "Local~/deployment=hawkular-rest-api.war"
        }, {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/r;Local~~/r;Local~%2Fdeployment%3Dhawkular-metrics-component.war",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/rt;Deployment",
            "name" : "Deployment",
            "id" : "Deployment"
          },
          "name" : "hawkular-metrics-component.war",
          "id" : "Local~/deployment=hawkular-metrics-component.war"
        }, {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/r;Local~~/r;Local~%2Fdeployment%3Dhawkular-commons-embedded-cassandra-ear.ear",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/rt;Deployment",
            "name" : "Deployment",
            "id" : "Deployment"
          },
          "name" : "hawkular-commons-embedded-cassandra-ear.ear",
          "id" : "Local~/deployment=hawkular-commons-embedded-cassandra-ear.ear"
        }, {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/r;Local~~/r;Local~%2Fdeployment%3Dhawkular-accounts.war",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/rt;Deployment",
            "name" : "Deployment",
            "id" : "Deployment"
          },
          "name" : "hawkular-accounts.war",
          "id" : "Local~/deployment=hawkular-accounts.war"
        }, {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/r;Local~~/r;Local~%2Fdeployment%3Dhawkular-btm-server.war",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/rt;Deployment",
            "name" : "Deployment",
            "id" : "Deployment"
          },
          "name" : "hawkular-btm-server.war",
          "id" : "Local~/deployment=hawkular-btm-server.war"
        }, {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/r;Local~~/r;Local~%2Fdeployment%3Dkeycloak-server.war",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/rt;Deployment",
            "name" : "Deployment",
            "id" : "Deployment"
          },
          "name" : "keycloak-server.war",
          "id" : "Local~/deployment=keycloak-server.war"
        }, {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/r;Local~~/r;Local~%2Fdeployment%3Dhawkular-console.war",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/rt;Deployment",
            "name" : "Deployment",
            "id" : "Deployment"
          },
          "name" : "hawkular-console.war",
          "id" : "Local~/deployment=hawkular-console.war"
        }, {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/r;Local~~/r;Local~%2Fsubsystem%3Dtransactions",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/rt;Transaction%20Manager",
            "name" : "Transaction Manager",
            "id" : "Transaction Manager"
          },
          "name" : "Transaction Manager",
          "id" : "Local~/subsystem=transactions"
        }, {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/r;Local~~/r;Local~%2Fsubsystem%3Dmessaging-activemq%2Fserver%3Ddefault",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/rt;Messaging%20Server",
            "name" : "Messaging Server",
            "id" : "Messaging Server"
          },
          "name" : "Messaging Server [default]",
          "id" : "Local~/subsystem=messaging-activemq/server=default"
        }, {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/r;Local~~/r;Local~%2Fsubsystem%3Dhawkular-wildfly-agent",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/rt;Hawkular%20WildFly%20Agent",
            "name" : "Hawkular WildFly Agent",
            "id" : "Hawkular WildFly Agent"
          },
          "name" : "Hawkular WildFly Agent",
          "id" : "Local~/subsystem=hawkular-wildfly-agent"
        } ]
    http_version: 
  recorded_at: Mon, 11 Apr 2016 16:51:39 GMT
recorded_with: VCR 3.0.1
