---
http_interactions:
- request:
    method: get
    uri: http://-XX-X-jdoe-X:password@localhost:8080/hawkular/inventory/status
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 401
      message: Unauthorized
    headers:
      Connection:
      - keep-alive
      Www-Authenticate:
      - Basic realm="ApplicationRealm"
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Content-Type:
      - text/html;charset=UTF-8
      Content-Length:
      - '71'
      Date:
      - Thu, 07 Jul 2016 22:04:24 GMT
    body:
      encoding: UTF-8
      string: "<html><head><title>Error</title></head><body>Unauthorized</body></html>"
    http_version: 
  recorded_at: Thu, 07 Jul 2016 22:04:24 GMT
recorded_with: VCR 3.0.3
