---
http_interactions:
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/traversal/type=f
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Wed, 13 Jul 2016 22:49:12 GMT
      X-Total-Count:
      - '2'
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '550'
      Link:
      - <http://localhost:8080/hawkular/inventory/traversal/type=f>; rel="current"
    body:
      encoding: ASCII-8BIT
      string: |-
        [ {
          "path" : "/t;hawkular/f;b0008021-533c-46b7-a7f1-b2bc7e0db5fc",
          "properties" : {
            "__identityHash" : "a4f79243357fadd4fa53a6d4ee923e4374309222"
          },
          "identityHash" : "a4f79243357fadd4fa53a6d4ee923e4374309222",
          "id" : "b0008021-533c-46b7-a7f1-b2bc7e0db5fc"
        }, {
          "path" : "/t;hawkular/f;45bf47d1-82bc-4638-8d81-6e6b36af903d-feed",
          "properties" : {
            "__identityHash" : "559125a58b94995df3fdde22c7d67aa3cfab23"
          },
          "identityHash" : "559125a58b94995df3fdde22c7d67aa3cfab23",
          "id" : "45bf47d1-82bc-4638-8d81-6e6b36af903d-feed"
        } ]
    http_version: 
  recorded_at: Wed, 13 Jul 2016 22:49:12 GMT
recorded_with: VCR 3.0.1
