MethodLength:
  Enabled: false
ClassLength:
  Enabled: false
ModuleLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
