---
http_interactions:
- request:
    method: get
    uri: https://<%= super_secret_username %>:<%= super_secret_password %>@127.0.0.1:8443/hawkular/inventory/traversal/f;<%= feed_uuid %>/mt;Total%20Space/rl;defines/type=m
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Host:
      - 127.0.0.1:8443
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Wed, 10 Aug 2016 22:35:49 GMT
      X-Total-Count:
      - '2'
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '1762'
      Link:
      - <https://127.0.0.1:8443/hawkular/inventory/traversal/f;<%= feed_uuid %>/mt;Total%20Space/rl;defines/type=m>;
        rel="current"
    body:
      encoding: UTF-8
      string: |-
        [ {
          "path" : "/t;hawkular/f;<%= feed_uuid %>/m;MI~R~%5B<%= feed_uuid %>%2Fplatform~%2FOPERATING_SYSTEM%3D<%= feed_uuid %>_OperatingSystem%2FFILE_STORE%3D~%5D~MT~Total%20Space",
          "properties" : {
            "__identityHash" : "1c6ad522edd8cb6bbc779b81dc84c2e5a26ac68"
          },
          "name" : "Total Space",
          "identityHash" : "1c6ad522edd8cb6bbc779b81dc84c2e5a26ac68",
          "type" : {
            "path" : "/t;hawkular/f;<%= feed_uuid %>/mt;Total%20Space",
            "name" : "Total Space",
            "identityHash" : "4753b6bbe4fad4dfd57fae8fc2d35f91af13e53",
            "unit" : "BYTES",
            "metricDataType" : "gauge",
            "collectionInterval" : 300,
            "id" : "Total Space"
          },
          "id" : "MI~R~[<%= feed_uuid %>/platform~/OPERATING_SYSTEM=<%= feed_uuid %>_OperatingSystem/FILE_STORE=~]~MT~Total Space"
        }, {
          "path" : "/t;hawkular/f;<%= feed_uuid %>/m;MI~R~%5B<%= feed_uuid %>%2Fplatform~%2FOPERATING_SYSTEM%3D<%= feed_uuid %>_OperatingSystem%2FFILE_STORE%3Dtmpfs%5D~MT~Total%20Space",
          "properties" : {
            "__identityHash" : "5cce8cfe50ab6842b983f03bfb98d7f652ec6ae8"
          },
          "name" : "Total Space",
          "identityHash" : "5cce8cfe50ab6842b983f03bfb98d7f652ec6ae8",
          "type" : {
            "path" : "/t;hawkular/f;<%= feed_uuid %>/mt;Total%20Space",
            "name" : "Total Space",
            "identityHash" : "4753b6bbe4fad4dfd57fae8fc2d35f91af13e53",
            "unit" : "BYTES",
            "metricDataType" : "gauge",
            "collectionInterval" : 300,
            "id" : "Total Space"
          },
          "id" : "MI~R~[<%= feed_uuid %>/platform~/OPERATING_SYSTEM=<%= feed_uuid %>_OperatingSystem/FILE_STORE=tmpfs]~MT~Total Space"
        } ]
    http_version:
  recorded_at: Wed, 10 Aug 2016 22:35:49 GMT
recorded_with: VCR 3.0.3
