---
http_interactions:
- request:
    method: get
    uri: https://<%= super_secret_username %>:<%= super_secret_password %>@127.0.0.1:8443/hawkular/inventory/traversal/f;<%= feed_uuid %>/rt;Datasource/rl;defines/type=r
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Host:
      - 127.0.0.1:8443
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Wed, 10 Aug 2016 22:35:49 GMT
      X-Total-Count:
      - '1'
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '608'
      Link:
      - <https://127.0.0.1:8443/hawkular/inventory/traversal/f;<%= feed_uuid %>/rt;Datasource/rl;defines/type=r>;
        rel="current"
    body:
      encoding: UTF-8
      string: |-
        [ {
          "path" : "/t;hawkular/f;<%= feed_uuid %>/r;Local~~/r;Local~%2Fsubsystem%3Ddatasources%2Fdata-source%3DExampleDS",
          "properties" : {
            "__identityHash" : "e5bba7c6c22ec4591bff4532ca14e989d1498c4"
          },
          "name" : "Datasource [ExampleDS]",
          "identityHash" : "e5bba7c6c22ec4591bff4532ca14e989d1498c4",
          "type" : {
            "path" : "/t;hawkular/f;<%= feed_uuid %>/rt;Datasource",
            "name" : "Datasource",
            "identityHash" : "b3291af08b396960f425871b493b6d9ee97e339f",
            "id" : "Datasource"
          },
          "id" : "Local~/subsystem=datasources/data-source=ExampleDS"
        } ]
    http_version: 
  recorded_at: Wed, 10 Aug 2016 22:35:49 GMT
- request:
    method: get
    uri: https://<%= super_secret_username %>:<%= super_secret_password %>@127.0.0.1:8443/hawkular/inventory/entity/f;<%= feed_uuid %>/r;Local~~/r;Local~%2Fsubsystem=datasources%2Fdata-source=ExampleDS/d;configuration
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Host:
      - 127.0.0.1:8443
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Wed, 10 Aug 2016 22:35:49 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '585'
    body:
      encoding: UTF-8
      string: |-
        {
          "path" : "/t;hawkular/f;<%= feed_uuid %>/r;Local~~/r;Local~%2Fsubsystem%3Ddatasources%2Fdata-source%3DExampleDS/d;configuration",
          "properties" : {
            "__identityHash" : "db85f6b08996789d6b315151197ef115897dc12"
          },
          "name" : "configuration",
          "identityHash" : "db85f6b08996789d6b315151197ef115897dc12",
          "value" : {
            "Username" : "sa",
            "Driver Name" : "h2",
            "JNDI Name" : "java:jboss/datasources/ExampleDS",
            "Connection URL" : "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE",
            "Enabled" : "true",
            "Password" : "sa"
          }
        }
    http_version: 
  recorded_at: Wed, 10 Aug 2016 22:35:49 GMT
recorded_with: VCR 3.0.3
