---
http_interactions:
- request:
    method: get
    uri: https://<%= super_secret_username %>:<%= super_secret_password %>@127.0.0.1:8443/hawkular/inventory/traversal/f;<%= feed_uuid %>/mt;Server%20Availability~Server%20Availability/rl;defines/type=m
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Host:
      - 127.0.0.1:8443
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Wed, 10 Aug 2016 22:35:49 GMT
      X-Total-Count:
      - '1'
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '836'
      Link:
      - <https://127.0.0.1:8443/hawkular/inventory/traversal/f;<%= feed_uuid %>/mt;Server%20Availability~Server%20Availability/rl;defines/type=m>;
        rel="current"
    body:
      encoding: UTF-8
      string: |-
        [ {
          "path" : "/t;hawkular/f;<%= feed_uuid %>/m;AI~R~%5B<%= feed_uuid %>%2FLocal~~%5D~AT~Server%20Availability~Server%20Availability",
          "properties" : {
            "__identityHash" : "f0713880a388aeaadf783b7e6d148c8ccd9156dd"
          },
          "name" : "Server Availability",
          "identityHash" : "f0713880a388aeaadf783b7e6d148c8ccd9156dd",
          "type" : {
            "path" : "/t;hawkular/f;<%= feed_uuid %>/mt;Server%20Availability~Server%20Availability",
            "name" : "Server Availability",
            "identityHash" : "69beedc2b0c5cf2f3d0484b9c1aa9e4cdcf93",
            "unit" : "NONE",
            "metricDataType" : "AVAILABILITY",
            "collectionInterval" : 30,
            "id" : "Server Availability~Server Availability"
          },
          "id" : "AI~R~[<%= feed_uuid %>/Local~~]~AT~Server Availability~Server Availability"
        } ]
    http_version: 
  recorded_at: Wed, 10 Aug 2016 22:35:50 GMT
recorded_with: VCR 3.0.3
