---
http_interactions:
- request:
    method: post
    uri: https://<%= super_secret_username %>:<%= super_secret_password %>@127.0.0.1:8443/hawkular/api/urls
    body:
      encoding: UTF-8
      string: '{"url":"http://bsd.de"}'
    headers:
      Accept:
      - "*/*"
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Content-Length:
      - '23'
      Host:
      - 127.0.0.1:8443
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Tue, 30 Aug 2016 16:03:28 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/hawkular.1.0.0+json
      Content-Length:
      - '44'
    body:
      encoding: UTF-8
      string: Url URL[url='http://bsd.de'] already exists.
    http_version: 
  recorded_at: Tue, 30 Aug 2016 16:03:28 GMT
recorded_with: VCR 3.0.3
