---
http_interactions:
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/tenant
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Tue, 22 Mar 2016 01:25:05 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '105'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf",
          "id" : "28026b36-8fe4-4332-84c8-524e173a68bf"
        }
    http_version:
  recorded_at: Tue, 22 Mar 2016 01:25:05 GMT
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/status
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Connection:
      - keep-alive
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Content-Type:
      - application/json
      Content-Length:
      - '234'
      Date:
      - Thu, 14 Jul 2016 00:08:07 GMT
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "Implementation-Version" : "0.17.2.Final",
          "Built-From-Git-SHA1" : "3c8ac6648aa0ec33643ae1b98faadc475d2c6f02",
          "Inventory-Implementation" : "org.hawkular.inventory.impl.tinkerpop.TinkerpopInventory",
          "Initialized" : "true"
        }
    http_version:
  recorded_at: Thu, 14 Jul 2016 00:08:07 GMT
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/tenant
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Thu, 14 Jul 2016 00:09:45 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '49'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;hawkular",
          "id" : "hawkular"
        }
    http_version:
  recorded_at: Thu, 14 Jul 2016 00:09:45 GMT
recorded_with: VCR 3.0.1
