---
http_interactions:
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/<%= feed_uuid %>/resources
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Mon, 13 Jun 2016 16:29:56 GMT
      X-Total-Count:
      - '2'
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '786'
      Link:
      - <http://localhost:8080/hawkular/inventory/feeds/<%= feed_uuid %>/resources>;
        rel="current"
    body:
      encoding: ASCII-8BIT
      string: |-
        [ {
          "path" : "/t;hawkular/f;<%= feed_uuid %>/r;platform~%2FOPERATING_SYSTEM%3D<%= feed_uuid %>_OperatingSystem",
          "name" : "<%= feed_uuid %>_OperatingSystem",
          "type" : {
            "path" : "/t;hawkular/f;<%= feed_uuid %>/rt;Operating%20System",
            "name" : "Operating System",
            "id" : "Operating System"
          },
          "id" : "platform~/OPERATING_SYSTEM=<%= feed_uuid %>_OperatingSystem"
        }, {
          "path" : "/t;hawkular/f;<%= feed_uuid %>/r;Local~~",
          "name" : "WildFly Server [Local]",
          "type" : {
            "path" : "/t;hawkular/f;<%= feed_uuid %>/rt;WildFly%20Server",
            "name" : "WildFly Server",
            "id" : "WildFly Server"
          },
          "id" : "Local~~"
        } ]
    http_version: 
  recorded_at: Mon, 13 Jun 2016 16:29:56 GMT
recorded_with: VCR 3.0.1
