---
http_interactions:
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/<%= feed_uuid %>/resourceTypes/Datasource/resources
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Thu, 05 May 2016 11:18:41 GMT
      X-Total-Count:
      - '2'
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '871'
      Link:
      - <http://localhost:8080/hawkular/inventory/feeds/<%= feed_uuid %>/resourceTypes/Datasource/resources>;
        rel="current"
    body:
      encoding: ASCII-8BIT
      string: |-
        [ {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/r;Local~~/r;Local~%2Fsubsystem%3Ddatasources%2Fdata-source%3DExampleDS",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/rt;Datasource",
            "name" : "Datasource",
            "id" : "Datasource"
          },
          "name" : "ExampleDS",
          "id" : "Local~/subsystem=datasources/data-source=ExampleDS"
        }, {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/r;Local~~/r;Local~%2Fsubsystem%3Ddatasources%2Fdata-source%3DKeycloakDS",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/rt;Datasource",
            "name" : "Datasource",
            "id" : "Datasource"
          },
          "name" : "KeycloakDS",
          "id" : "Local~/subsystem=datasources/data-source=KeycloakDS"
        } ]
    http_version: 
  recorded_at: Thu, 05 May 2016 11:18:41 GMT
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/<%= feed_uuid %>/resources/Local~%2Fsubsystem=datasources%2Fdata-source=ExampleDS/data?dataType=configuration
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 404
      message: Not Found
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Thu, 05 May 2016 11:18:41 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '508'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "errorMsg" : "No DataEntity found on any of the following paths: [[CanonicalPaths[/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/r;Local~%2Fsubsystem%3Ddatasources%2Fdata-source%3DExampleDS/d;configuration]]]",
          "details" : {
            "entityType" : "DataEntity",
            "path" : [ [ {
              "paths" : [ "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/r;Local~%2Fsubsystem%3Ddatasources%2Fdata-source%3DExampleDS/d;configuration" ]
            } ] ]
          }
        }
    http_version: 
  recorded_at: Thu, 05 May 2016 11:18:41 GMT
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/<%= feed_uuid %>/resources/Local~%2Fsubsystem=datasources%2Fdata-source=KeycloakDS/data?dataType=configuration
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 404
      message: Not Found
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Thu, 05 May 2016 11:18:41 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '510'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "errorMsg" : "No DataEntity found on any of the following paths: [[CanonicalPaths[/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/r;Local~%2Fsubsystem%3Ddatasources%2Fdata-source%3DKeycloakDS/d;configuration]]]",
          "details" : {
            "entityType" : "DataEntity",
            "path" : [ [ {
              "paths" : [ "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= feed_uuid %>/r;Local~%2Fsubsystem%3Ddatasources%2Fdata-source%3DKeycloakDS/d;configuration" ]
            } ] ]
          }
        }
    http_version: 
  recorded_at: Thu, 05 May 2016 11:18:41 GMT
recorded_with: VCR 3.0.1
