---
http_interactions:
- request:
    method: get
    uri: https://<%= super_secret_username %>:<%= super_secret_password %>@hawkular.torii.gva.redhat.com/hawkular/inventory/feeds
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - nginx/1.6.3
      Date:
      - Fri, 27 May 2016 17:17:09 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '148'
      Connection:
      - keep-alive
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Pragma:
      - no-cache
      X-Total-Count:
      - '1'
      Link:
      - <http://hawkular.torii.gva.redhat.com/hawkular/inventory/feeds>; rel="current"
      Strict-Transport-Security:
      - max-age=31536000
    body:
      encoding: ASCII-8BIT
      string: |-
        [ {
          "path" : "/t;0b6bda15-0d73-4375-b7a0-6318d53d7ac5/f;7ee8f677-9489-4da6-abb4-46b7e4bc228c",
          "id" : "7ee8f677-9489-4da6-abb4-46b7e4bc228c"
        } ]
    http_version: 
  recorded_at: Fri, 27 May 2016 17:15:26 GMT
recorded_with: VCR 3.0.1
