---
http_interactions:
- request:
    method: get
    uri: http://jdoe:<%= super_secret_password %>@localhost:8080/hawkular/inventory/traversal/f;<%= feed_uuid %>/rt;WildFly%20Server/rl;defines/type=r
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Wed, 13 Jul 2016 21:46:24 GMT
      X-Total-Count:
      - '1'
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '511'
      Link:
      - <http://localhost:8080/hawkular/inventory/traversal/f;<%= feed_uuid %>/rt;WildFly%20Server/rl;defines/type=r>;
        rel="current"
    body:
      encoding: ASCII-8BIT
      string: |-
        [ {
          "path" : "/t;hawkular/f;<%= feed_uuid %>/r;Local~~",
          "properties" : {
            "__identityHash" : "706a325c01e60343eb4f6e2aef257a333fd7"
          },
          "name" : "WildFly Server [Local]",
          "identityHash" : "706a325c01e60343eb4f6e2aef257a333fd7",
          "type" : {
            "path" : "/t;hawkular/f;<%= feed_uuid %>/rt;WildFly%20Server",
            "name" : "WildFly Server",
            "identityHash" : "617542c89b86e3ce52b819c1deae7ca37cf7851",
            "id" : "WildFly Server"
          },
          "id" : "Local~~"
        } ]
    http_version: 
  recorded_at: Wed, 13 Jul 2016 21:46:24 GMT
- request:
    method: get
    uri: http://jdoe:<%= super_secret_password %>@localhost:8080/hawkular/inventory/entity/f;<%= feed_uuid %>/r;Local~~/d;configuration
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Wed, 13 Jul 2016 21:46:24 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '571'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;hawkular/f;<%= feed_uuid %>/r;Local~~/d;configuration",
          "properties" : {
            "__identityHash" : "82d7496d2787d8af42f9cd45868c31b8cadc9d"
          },
          "name" : "configuration",
          "identityHash" : "82d7496d2787d8af42f9cd45868c31b8cadc9d",
          "value" : {
            "Suspend State" : "RUNNING",
            "Bound Address" : "127.0.0.1",
            "Running Mode" : "NORMAL",
            "Node Name" : "localhost",
            "Server State" : "running",
            "Hostname" : "localhost.localdomain",
            "UUID" : "<%= feed_uuid %>",
            "Name" : "localhost"
          }
        }
    http_version: 
  recorded_at: Wed, 13 Jul 2016 21:46:24 GMT
recorded_with: VCR 3.0.1
