---
http_interactions:
- request:
    method: post
    uri: http://jdoe:<%= super_secret_password %>@localhost:8080/hawkular/inventory/entity/feed
    body:
      encoding: UTF-8
      string: '{"properties":{},"id":"feed_1123sdn","name":null,"outgoing":{},"incoming":{}}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Content-Length:
      - '77'
      User-Agent:
      - Ruby
  response:
    status:
      code: 201
      message: Created
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Location:
      - http://localhost:8080/hawkular/inventory/entity/f;feed_1123sdn
      Date:
      - Wed, 13 Jul 2016 21:46:25 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '131'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;hawkular/f;feed_1123sdn",
          "identityHash" : "e153d6e14c5bd12f51dcdc16a0493afbd0298dcb",
          "id" : "feed_1123sdn"
        }
    http_version: 
  recorded_at: Wed, 13 Jul 2016 21:46:25 GMT
- request:
    method: delete
    uri: http://jdoe:<%= super_secret_password %>@localhost:8080/hawkular/inventory/entity/f;feed_1123sdn
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 204
      message: No Content
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Wed, 13 Jul 2016 21:46:25 GMT
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Wed, 13 Jul 2016 21:46:25 GMT
- request:
    method: get
    uri: http://jdoe:<%= super_secret_password %>@localhost:8080/hawkular/inventory/traversal/type=f
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Wed, 13 Jul 2016 21:46:25 GMT
      X-Total-Count:
      - '2'
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '538'
      Link:
      - <http://localhost:8080/hawkular/inventory/traversal/type=f>; rel="current"
    body:
      encoding: ASCII-8BIT
      string: |-
        [ {
          "path" : "/t;hawkular/f;<%= feed_uuid %>",
          "properties" : {
            "__identityHash" : "31eb16be1a46a9978e8619a08dc3a0a9a5c5c2"
          },
          "identityHash" : "31eb16be1a46a9978e8619a08dc3a0a9a5c5c2",
          "id" : "<%= feed_uuid %>"
        }, {
          "path" : "/t;hawkular/f;feed_1123sdncisud6237ui23hjbdscuzsad",
          "properties" : {
            "__identityHash" : "c5ef96a36ea11f6a72066f685b5d1d8b9d1daaf"
          },
          "identityHash" : "c5ef96a36ea11f6a72066f685b5d1d8b9d1daaf",
          "id" : "feed_1123sdncisud6237ui23hjbdscuzsad"
        } ]
    http_version: 
  recorded_at: Wed, 13 Jul 2016 21:46:25 GMT
recorded_with: VCR 3.0.1
