---
http_interactions:
- request:
    method: post
    uri: http://jdoe:<%= super_secret_password %>@localhost:8080/hawkular/inventory/entity/feed
    body:
      encoding: UTF-8
      string: '{"properties":{},"id":"feed_may_exist","name":null,"outgoing":{},"incoming":{}}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Content-Length:
      - '79'
      User-Agent:
      - Ruby
  response:
    status:
      code: 409
      message: Conflict
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Wed, 13 Jul 2016 21:46:26 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '663'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "errorMsg" : "Feed with id 'Feed[path='/t;hawkular/f;feed_may_exist']' has been already registered. Entity with id 'feed_may_exist' already exists at some of the positions: [[Types[Tenant], Ids[hawkular], Related[, rel='contains', role=SOURCE], Types[Feed], Ids[feed_may_exist]]]",
          "details" : {
            "entityId" : "feed_may_exist",
            "paths" : [ [ {
              "types" : [ "org.hawkular.inventory.api.model.Tenant" ]
            }, {
              "ids" : [ "hawkular" ]
            }, {
              "relationshipName" : "contains",
              "entityRole" : "SOURCE"
            }, {
              "types" : [ "org.hawkular.inventory.api.model.Feed" ]
            }, {
              "ids" : [ "feed_may_exist" ]
            } ] ]
          }
        }
    http_version: 
  recorded_at: Wed, 13 Jul 2016 21:46:26 GMT
- request:
    method: get
    uri: http://jdoe:<%= super_secret_password %>@localhost:8080/hawkular/inventory/entity/f;feed_may_exist
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Wed, 13 Jul 2016 21:46:26 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '225'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;hawkular/f;feed_may_exist",
          "properties" : {
            "__identityHash" : "95604cd341ec20d5a059792fbc18603bf754fbcc"
          },
          "identityHash" : "95604cd341ec20d5a059792fbc18603bf754fbcc",
          "id" : "feed_may_exist"
        }
    http_version: 
  recorded_at: Wed, 13 Jul 2016 21:46:26 GMT
- request:
    method: post
    uri: http://jdoe:<%= super_secret_password %>@localhost:8080/hawkular/inventory/entity/f;feed_may_exist/resourceType
    body:
      encoding: UTF-8
      string: '{"properties":{},"id":"rt-123","name":"ResourceType","outgoing":{},"incoming":{}}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Content-Length:
      - '81'
      User-Agent:
      - Ruby
  response:
    status:
      code: 409
      message: Conflict
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Wed, 13 Jul 2016 21:46:26 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '107'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "errorMsg" : "Entity with id 'null' already exists at some of the positions: null",
          "details" : { }
        }
    http_version: 
  recorded_at: Wed, 13 Jul 2016 21:46:26 GMT
- request:
    method: get
    uri: http://jdoe:<%= super_secret_password %>@localhost:8080/hawkular/inventory/entity/f;feed_may_exist/rt;rt-123
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Wed, 13 Jul 2016 21:46:26 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '162'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;hawkular/f;feed_may_exist/rt;rt-123",
          "name" : "ResourceType",
          "identityHash" : "30a52c53a93cb102e499367ecc55ed8a03b0b1",
          "id" : "rt-123"
        }
    http_version: 
  recorded_at: Wed, 13 Jul 2016 21:46:26 GMT
- request:
    method: post
    uri: http://jdoe:<%= super_secret_password %>@localhost:8080/hawkular/inventory/entity/f;feed_may_exist/resource
    body:
      encoding: UTF-8
      string: '{"properties":{"version":1.0},"id":"r123","name":"My Resource","outgoing":{},"incoming":{},"resourceTypePath":"/t;hawkular/f;feed_may_exist/rt;rt-123"}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      Content-Length:
      - '151'
      User-Agent:
      - Ruby
  response:
    status:
      code: 201
      message: Created
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Location:
      - http://localhost:8080/hawkular/inventory/entity/f;feed_may_exist/r;r123
      Date:
      - Wed, 13 Jul 2016 21:46:26 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '383'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;hawkular/f;feed_may_exist/r;r123",
          "properties" : {
            "version" : 1.0
          },
          "name" : "My Resource",
          "identityHash" : "3be2debda577083937e8830525b1bef4fa48",
          "type" : {
            "path" : "/t;hawkular/f;feed_may_exist/rt;rt-123",
            "name" : "ResourceType",
            "identityHash" : "30a52c53a93cb102e499367ecc55ed8a03b0b1",
            "id" : "rt-123"
          },
          "id" : "r123"
        }
    http_version: 
  recorded_at: Wed, 13 Jul 2016 21:46:26 GMT
- request:
    method: get
    uri: http://jdoe:<%= super_secret_password %>@localhost:8080/hawkular/inventory/entity/f;feed_may_exist/r;r123
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Hawkular-Tenant:
      - hawkular
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Wed, 13 Jul 2016 21:46:26 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '446'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;hawkular/f;feed_may_exist/r;r123",
          "properties" : {
            "__identityHash" : "3be2debda577083937e8830525b1bef4fa48",
            "version" : 1.0
          },
          "name" : "My Resource",
          "identityHash" : "3be2debda577083937e8830525b1bef4fa48",
          "type" : {
            "path" : "/t;hawkular/f;feed_may_exist/rt;rt-123",
            "name" : "ResourceType",
            "identityHash" : "30a52c53a93cb102e499367ecc55ed8a03b0b1",
            "id" : "rt-123"
          },
          "id" : "r123"
        }
    http_version: 
  recorded_at: Wed, 13 Jul 2016 21:46:26 GMT
recorded_with: VCR 3.0.1
