---
http_interactions:
- request:
    method: post
    uri: http://jdoe:password@localhost:8080/hawkular/metrics/availability/<%= id %>/data
    body:
      encoding: UTF-8
      string: '[{"timestamp":<%= now - 50 %>,"value":"up"},{"timestamp":<%= now - 40 %>,"value":"up"},{"timestamp":<%= now - 30 %>,"value":"down"},{"timestamp":<%= now - 20 %>,"value":"down"},{"timestamp":<%= now - 10 %>,"value":"down"},{"timestamp":<%= now  %>,"value":"up"}]'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Hawkular-Tenant:
      - vcr-test
      Content-Type:
      - application/json
      Content-Length:
      - '253'
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Connection:
      - keep-alive
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Content-Length:
      - '0'
      Date:
      - Thu, 30 Jun 2016 23:03:28 GMT
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Thu, 30 Jun 2016 23:03:28 GMT
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/metrics/availability/<%= id %>/data/?distinct=true&order=ASC
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Hawkular-Tenant:
      - vcr-test
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Thu, 30 Jun 2016 23:03:28 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '126'
    body:
      encoding: UTF-8
      string: '[{"timestamp":<%= now - 50 %>,"value":"up"},{"timestamp":<%= now - 30 %>,"value":"down"},{"timestamp":<%= now  %>,"value":"up"}]'
    http_version: 
  recorded_at: Thu, 30 Jun 2016 23:03:28 GMT
recorded_with: VCR 3.0.3
