---
http_interactions:
- request:
    method: get
    uri: http://localhost:8080/hawkular/alerter/prometheus/endpoint
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - "*/*"
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Host:
      - localhost:8080
  response:
    status:
      code: 200
      message: OK
    headers:
      Connection:
      - keep-alive
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Content-Type:
      - application/json
      Content-Length:
      - '21'
      Date:
      - Tue, 28 Nov 2017 10:51:11 GMT
    body:
      encoding: UTF-8
      string: http://localhost:9090
    http_version: 
  recorded_at: Tue, 28 Nov 2017 10:51:11 GMT
- request:
    method: get
    uri: http://localhost:9090/api/v1/query_range?end=2017-11-28T15:00:00Z&query=up%7Bfeed_id=%22attilan%22%7D&start=2017-11-28T10:00:00Z&step=60m
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - identity
      User-Agent:
      - hawkular-client-ruby
      Content-Type:
      - application/json
      Host:
      - localhost:9090
  response:
    status:
      code: 200
      message: OK
    headers:
      Access-Control-Allow-Headers:
      - Accept, Authorization, Content-Type, Origin
      Access-Control-Allow-Methods:
      - GET, OPTIONS
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Expose-Headers:
      - Date
      Content-Type:
      - application/json
      Date:
      - Tue, 28 Nov 2017 10:51:11 GMT
      Content-Length:
      - '184'
    body:
      encoding: UTF-8
      string: '{"status":"success","data":{"resultType":"matrix","result":[{"metric":{"__name__":"up","feed_id":"attilan","instance":"127.0.0.1:9779","job":"hawkular"},"values":[[1511863200,"1"]]}]}}'
    http_version: 
  recorded_at: Tue, 28 Nov 2017 10:51:11 GMT
recorded_with: VCR 3.0.3
