---
http_interactions:
- request:
    method: post
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/
    body:
      encoding: UTF-8
      string: '{"properties":{},"id":"<%= uuid_prefix %>-feed","name":null,"outgoing":{},"incoming":{}}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      Content-Length:
      - '106'
      User-Agent:
      - Ruby
  response:
    status:
      code: 201
      message: Created
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Location:
      - http://localhost:8080/hawkular/inventory/feeds/<%= uuid_prefix %>-feed
      Date:
      - Mon, 11 Apr 2016 16:51:45 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '154'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= uuid_prefix %>-feed",
          "id" : "<%= uuid_prefix %>-feed"
        }
    http_version: 
  recorded_at: Mon, 11 Apr 2016 16:51:45 GMT
- request:
    method: post
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/<%= uuid_prefix %>-feed/resourceTypes
    body:
      encoding: UTF-8
      string: '{"properties":{},"id":"<%= uuid_prefix %>-rt-123","name":"ResourceType","outgoing":{},"incoming":{}}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      Content-Length:
      - '118'
      User-Agent:
      - Ruby
  response:
    status:
      code: 201
      message: Created
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Location:
      - http://localhost:8080/hawkular/inventory/feeds/<%= uuid_prefix %>-feed/resourceTypes/<%= uuid_prefix %>-rt-123
      Date:
      - Mon, 11 Apr 2016 16:51:45 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '230'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= uuid_prefix %>-feed/rt;<%= uuid_prefix %>-rt-123",
          "name" : "ResourceType",
          "id" : "<%= uuid_prefix %>-rt-123"
        }
    http_version: 
  recorded_at: Mon, 11 Apr 2016 16:51:45 GMT
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/<%= uuid_prefix %>-feed/resourceTypes/<%= uuid_prefix %>-rt-123
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Mon, 11 Apr 2016 16:51:45 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '230'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= uuid_prefix %>-feed/rt;<%= uuid_prefix %>-rt-123",
          "name" : "ResourceType",
          "id" : "<%= uuid_prefix %>-rt-123"
        }
    http_version: 
  recorded_at: Mon, 11 Apr 2016 16:51:45 GMT
- request:
    method: post
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/<%= uuid_prefix %>-feed/resources
    body:
      encoding: UTF-8
      string: '{"properties":{"version":1.0},"id":"<%= uuid_prefix %>-r126","name":"My
        Resource 1","outgoing":{},"incoming":{},"resourceTypePath":"/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= uuid_prefix %>-feed/rt;<%= uuid_prefix %>-rt-123"}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      Content-Length:
      - '282'
      User-Agent:
      - Ruby
  response:
    status:
      code: 201
      message: Created
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Location:
      - http://localhost:8080/hawkular/inventory/feeds/<%= uuid_prefix %>-feed/resources/<%= uuid_prefix %>-r126
      Date:
      - Mon, 11 Apr 2016 16:51:45 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '521'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= uuid_prefix %>-feed/r;<%= uuid_prefix %>-r126",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= uuid_prefix %>-feed/rt;<%= uuid_prefix %>-rt-123",
            "name" : "ResourceType",
            "id" : "<%= uuid_prefix %>-rt-123"
          },
          "properties" : {
            "version" : 1.0
          },
          "name" : "My Resource 1",
          "id" : "<%= uuid_prefix %>-r126"
        }
    http_version: 
  recorded_at: Mon, 11 Apr 2016 16:51:45 GMT
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/<%= uuid_prefix %>-feed/resources/<%= uuid_prefix %>-r126
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Mon, 11 Apr 2016 16:51:45 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '521'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= uuid_prefix %>-feed/r;<%= uuid_prefix %>-r126",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= uuid_prefix %>-feed/rt;<%= uuid_prefix %>-rt-123",
            "name" : "ResourceType",
            "id" : "<%= uuid_prefix %>-rt-123"
          },
          "properties" : {
            "version" : 1.0
          },
          "name" : "My Resource 1",
          "id" : "<%= uuid_prefix %>-r126"
        }
    http_version: 
  recorded_at: Mon, 11 Apr 2016 16:51:45 GMT
- request:
    method: post
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/<%= uuid_prefix %>-feed/resources
    body:
      encoding: UTF-8
      string: '{"properties":{"version":1.1},"id":"<%= uuid_prefix %>-r127","name":"My
        Resource 2","outgoing":{},"incoming":{},"resourceTypePath":"/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= uuid_prefix %>-feed/rt;<%= uuid_prefix %>-rt-123"}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      Content-Length:
      - '282'
      User-Agent:
      - Ruby
  response:
    status:
      code: 201
      message: Created
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Location:
      - http://localhost:8080/hawkular/inventory/feeds/<%= uuid_prefix %>-feed/resources/<%= uuid_prefix %>-r127
      Date:
      - Mon, 11 Apr 2016 16:51:45 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '521'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= uuid_prefix %>-feed/r;<%= uuid_prefix %>-r127",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= uuid_prefix %>-feed/rt;<%= uuid_prefix %>-rt-123",
            "name" : "ResourceType",
            "id" : "<%= uuid_prefix %>-rt-123"
          },
          "properties" : {
            "version" : 1.1
          },
          "name" : "My Resource 2",
          "id" : "<%= uuid_prefix %>-r127"
        }
    http_version: 
  recorded_at: Mon, 11 Apr 2016 16:51:45 GMT
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/<%= uuid_prefix %>-feed/resources/<%= uuid_prefix %>-r127
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Mon, 11 Apr 2016 16:51:45 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '521'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= uuid_prefix %>-feed/r;<%= uuid_prefix %>-r127",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= uuid_prefix %>-feed/rt;<%= uuid_prefix %>-rt-123",
            "name" : "ResourceType",
            "id" : "<%= uuid_prefix %>-rt-123"
          },
          "properties" : {
            "version" : 1.1
          },
          "name" : "My Resource 2",
          "id" : "<%= uuid_prefix %>-r127"
        }
    http_version: 
  recorded_at: Mon, 11 Apr 2016 16:51:45 GMT
- request:
    method: post
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/<%= uuid_prefix %>-feed/resources
    body:
      encoding: UTF-8
      string: '{"properties":{"version":1.2},"id":"<%= uuid_prefix %>-r128","name":"My
        Resource 3","outgoing":{},"incoming":{},"resourceTypePath":"/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= uuid_prefix %>-feed/rt;<%= uuid_prefix %>-rt-123"}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      Content-Length:
      - '282'
      User-Agent:
      - Ruby
  response:
    status:
      code: 201
      message: Created
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Location:
      - http://localhost:8080/hawkular/inventory/feeds/<%= uuid_prefix %>-feed/resources/<%= uuid_prefix %>-r128
      Date:
      - Mon, 11 Apr 2016 16:51:45 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '521'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= uuid_prefix %>-feed/r;<%= uuid_prefix %>-r128",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= uuid_prefix %>-feed/rt;<%= uuid_prefix %>-rt-123",
            "name" : "ResourceType",
            "id" : "<%= uuid_prefix %>-rt-123"
          },
          "properties" : {
            "version" : 1.2
          },
          "name" : "My Resource 3",
          "id" : "<%= uuid_prefix %>-r128"
        }
    http_version: 
  recorded_at: Mon, 11 Apr 2016 16:51:45 GMT
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/<%= uuid_prefix %>-feed/resources/<%= uuid_prefix %>-r128
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Mon, 11 Apr 2016 16:51:45 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '521'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= uuid_prefix %>-feed/r;<%= uuid_prefix %>-r128",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;<%= uuid_prefix %>-feed/rt;<%= uuid_prefix %>-rt-123",
            "name" : "ResourceType",
            "id" : "<%= uuid_prefix %>-rt-123"
          },
          "properties" : {
            "version" : 1.2
          },
          "name" : "My Resource 3",
          "id" : "<%= uuid_prefix %>-r128"
        }
    http_version: 
  recorded_at: Mon, 11 Apr 2016 16:51:45 GMT
- request:
    method: delete
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/<%= uuid_prefix %>-feed
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 204
      message: No Content
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Mon, 11 Apr 2016 16:51:46 GMT
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Mon, 11 Apr 2016 16:51:46 GMT
recorded_with: VCR 3.0.1
