---
http_interactions:
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/tenant
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Encoding:
      - gzip
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/9
      Pragma:
      - no-cache
      Date:
      - Fri, 06 Nov 2015 19:45:47 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '85'
    body:
      encoding: ASCII-8BIT
      string: !binary |-
        H4sIAAAAAAAAAKvmUlBQKkgsyVBSsFJQ0i+xNrIwMDJLMjbTtUhLNdE1MTY2
        0rUwSbbQNTUySTU0N040s0hKU9IB6cpMAeshSgNXLQAnmwH5aQAAAA==
    http_version: 
  recorded_at: Fri, 06 Nov 2015 19:45:47 GMT
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/test/does%20not%20exist/resourceTypes
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Encoding:
      - gzip
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/9
      Pragma:
      - no-cache
      Date:
      - Fri, 06 Nov 2015 19:45:47 GMT
      X-Total-Count:
      - '-1'
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '23'
      Link:
      - <http://localhost:8080/hawkular/inventory/test/does%20not%20exist/resourceTypes>;
        rel="current"
    body:
      encoding: ASCII-8BIT
      string: !binary |-
        H4sIAAAAAAAAAItWiAUAqBH2HwMAAAA=
    http_version: 
  recorded_at: Fri, 06 Nov 2015 19:45:47 GMT
recorded_with: VCR 3.0.0
