---
http_interactions:
- request:
    method: post
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/
    body:
      encoding: UTF-8
      string: '{"properties":{},"id":"feed_may_exist","name":null,"outgoing":{},"incoming":{}}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      Content-Length:
      - '79'
      User-Agent:
      - Ruby
  response:
    status:
      code: 409
      message: Conflict
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Thu, 21 Apr 2016 14:01:18 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '747'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "errorMsg" : "Feed with id 'Feed[path='/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist']' has been already registered. Entity with id 'feed_may_exist' already exists at some of the positions: [[Types[Tenant], Ids[28026b36-8fe4-4332-84c8-524e173a68bf], Related[, rel='contains', role=SOURCE], Types[Feed], Ids[feed_may_exist]]]",
          "details" : {
            "entityId" : "feed_may_exist",
            "paths" : [ [ {
              "types" : [ "org.hawkular.inventory.api.model.Tenant" ]
            }, {
              "ids" : [ "28026b36-8fe4-4332-84c8-524e173a68bf" ]
            }, {
              "relationshipName" : "contains",
              "entityRole" : "SOURCE"
            }, {
              "types" : [ "org.hawkular.inventory.api.model.Feed" ]
            }, {
              "ids" : [ "feed_may_exist" ]
            } ] ]
          }
        }
    http_version: 
  recorded_at: Thu, 21 Apr 2016 14:01:18 GMT
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/feed_may_exist
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Thu, 21 Apr 2016 14:01:18 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '100'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist",
          "id" : "feed_may_exist"
        }
    http_version: 
  recorded_at: Thu, 21 Apr 2016 14:01:18 GMT
- request:
    method: post
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/feed_may_exist/resourceTypes
    body:
      encoding: UTF-8
      string: '{"properties":{},"id":"rt-123-1","name":"ResourceType","outgoing":{},"incoming":{}}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      Content-Length:
      - '83'
      User-Agent:
      - Ruby
  response:
    status:
      code: 409
      message: Conflict
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Thu, 21 Apr 2016 14:01:18 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '107'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "errorMsg" : "Entity with id 'null' already exists at some of the positions: null",
          "details" : { }
        }
    http_version: 
  recorded_at: Thu, 21 Apr 2016 14:01:18 GMT
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/feed_may_exist/resourceTypes/rt-123-1
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Thu, 21 Apr 2016 14:01:18 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '133'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist/rt;rt-123-1",
          "name" : "ResourceType",
          "id" : "rt-123-1"
        }
    http_version: 
  recorded_at: Thu, 21 Apr 2016 14:01:18 GMT
- request:
    method: post
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/feed_may_exist/resources
    body:
      encoding: UTF-8
      string: '{"properties":{},"id":"r124-a","name":"Res-a","outgoing":{},"incoming":{},"resourceTypePath":"/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist/rt;rt-123-1"}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      Content-Length:
      - '164'
      User-Agent:
      - Ruby
  response:
    status:
      code: 409
      message: Conflict
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Thu, 21 Apr 2016 14:01:18 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '107'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "errorMsg" : "Entity with id 'null' already exists at some of the positions: null",
          "details" : { }
        }
    http_version: 
  recorded_at: Thu, 21 Apr 2016 14:01:18 GMT
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/feed_may_exist/resources/r124-a
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Thu, 21 Apr 2016 14:01:18 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '275'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist/r;r124-a",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist/rt;rt-123-1",
            "name" : "ResourceType",
            "id" : "rt-123-1"
          },
          "name" : "Res-a",
          "id" : "r124-a"
        }
    http_version: 
  recorded_at: Thu, 21 Apr 2016 14:01:18 GMT
- request:
    method: post
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/feed_may_exist/resources/r124-a
    body:
      encoding: UTF-8
      string: '{"properties":{},"id":"r124-b","name":"Res-a","outgoing":{},"incoming":{},"resourceTypePath":"/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist/rt;rt-123-1"}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      Content-Length:
      - '164'
      User-Agent:
      - Ruby
  response:
    status:
      code: 409
      message: Conflict
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Thu, 21 Apr 2016 14:01:18 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '107'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "errorMsg" : "Entity with id 'null' already exists at some of the positions: null",
          "details" : { }
        }
    http_version: 
  recorded_at: Thu, 21 Apr 2016 14:01:18 GMT
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/feed_may_exist/resources/r124-a/r124-b
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Thu, 21 Apr 2016 14:01:18 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '284'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist/r;r124-a/r;r124-b",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist/rt;rt-123-1",
            "name" : "ResourceType",
            "id" : "rt-123-1"
          },
          "name" : "Res-a",
          "id" : "r124-b"
        }
    http_version: 
  recorded_at: Thu, 21 Apr 2016 14:01:18 GMT
- request:
    method: post
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/feed_may_exist/metricTypes
    body:
      encoding: UTF-8
      string: '{"id":"mt-124-a","type":"GAUGE","unit":"NONE","collectionInterval":60}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      Content-Length:
      - '70'
      User-Agent:
      - Ruby
  response:
    status:
      code: 409
      message: Conflict
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Thu, 21 Apr 2016 14:01:19 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '107'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "errorMsg" : "Entity with id 'null' already exists at some of the positions: null",
          "details" : { }
        }
    http_version: 
  recorded_at: Thu, 21 Apr 2016 14:01:19 GMT
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/feed_may_exist/metricTypes/mt-124-a
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Thu, 21 Apr 2016 14:01:19 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '174'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist/mt;mt-124-a",
          "unit" : "NONE",
          "type" : "GAUGE",
          "collectionInterval" : 60,
          "id" : "mt-124-a"
        }
    http_version: 
  recorded_at: Thu, 21 Apr 2016 14:01:19 GMT
- request:
    method: post
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/feed_may_exist/metrics
    body:
      encoding: UTF-8
      string: '{"id":"m-124-a","name":"MetricUnderNestedResource","metricTypePath":"/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist/mt;mt-124-a"}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      Content-Length:
      - '139'
      User-Agent:
      - Ruby
  response:
    status:
      code: 409
      message: Conflict
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Thu, 21 Apr 2016 14:01:19 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '107'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "errorMsg" : "Entity with id 'null' already exists at some of the positions: null",
          "details" : { }
        }
    http_version: 
  recorded_at: Thu, 21 Apr 2016 14:01:19 GMT
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/feed_may_exist/metrics/m-124-a
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Thu, 21 Apr 2016 14:01:19 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '342'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist/m;m-124-a",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist/mt;mt-124-a",
            "unit" : "NONE",
            "type" : "GAUGE",
            "collectionInterval" : 60,
            "id" : "mt-124-a"
          },
          "name" : "MetricUnderNestedResource",
          "id" : "m-124-a"
        }
    http_version: 
  recorded_at: Thu, 21 Apr 2016 14:01:19 GMT
- request:
    method: post
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/feed_may_exist/resources/r124-a/r124-b/metrics
    body:
      encoding: UTF-8
      string: '["/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist/m;m-124-a"]'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      Content-Length:
      - '70'
      User-Agent:
      - Ruby
  response:
    status:
      code: 409
      message: Conflict
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Thu, 21 Apr 2016 14:01:19 GMT
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '381'
    body:
      encoding: ASCII-8BIT
      string: |-
        {
          "errorMsg" : "Relation with id 'incorporates' already exists at some of the positions: [[CanonicalPaths[/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist/r;r124-a/r;r124-b]]]",
          "details" : {
            "relationshipNameOrId" : "incorporates",
            "paths" : [ [ {
              "paths" : [ "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist/r;r124-a/r;r124-b" ]
            } ] ]
          }
        }
    http_version: 
  recorded_at: Thu, 21 Apr 2016 14:01:19 GMT
- request:
    method: get
    uri: http://jdoe:password@localhost:8080/hawkular/inventory/feeds/feed_may_exist/resources/r124-a/r124-b/metrics
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      Content-Type:
      - application/json
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Expires:
      - '0'
      Cache-Control:
      - no-cache, no-store, must-revalidate
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Pragma:
      - no-cache
      Date:
      - Thu, 21 Apr 2016 14:01:19 GMT
      X-Total-Count:
      - '1'
      Connection:
      - keep-alive
      Content-Type:
      - application/json
      Content-Length:
      - '346'
      Link:
      - <http://localhost:8080/hawkular/inventory/feeds/feed_may_exist/resources/r124-a/r124-b/metrics>;
        rel="current"
    body:
      encoding: ASCII-8BIT
      string: |-
        [ {
          "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist/m;m-124-a",
          "type" : {
            "path" : "/t;28026b36-8fe4-4332-84c8-524e173a68bf/f;feed_may_exist/mt;mt-124-a",
            "unit" : "NONE",
            "type" : "GAUGE",
            "collectionInterval" : 60,
            "id" : "mt-124-a"
          },
          "name" : "MetricUnderNestedResource",
          "id" : "m-124-a"
        } ]
    http_version: 
  recorded_at: Thu, 21 Apr 2016 14:01:19 GMT
recorded_with: VCR 3.0.1
